version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: hiremind_postgres_dev
    environment:
      POSTGRES_USER: hiremind_user
      POSTGRES_PASSWORD: hiremind_password
      POSTGRES_DB: hiremind_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U hiremind_user" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - hiremind_dev_network

  redis:
    image: redis:7-alpine
    container_name: hiremind_redis_dev
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - hiremind_dev_network

  consumer-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hiremind_consumer_service_dev
    environment:
      - PORT=50051
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=hiremind_user
      - DB_PASSWORD=hiremind_password
      - DB_NAME=hiremind_db
      - DB_SSLMODE=disable
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DB=0
      - LOG_LEVEL=debug
    ports:
      - "50051:50051"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - hiremind_dev_network
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:


networks:
  hiremind_dev_network:
    driver: bridge
